version: 2
models:
- name: fct_order_items
  description: Fact table for order_items with business metrics
  tags:
  - marts
  - fct
  meta:
    model_type: fact
    source_models:
    - stg_order_items
- name: fct_orders
  description: Fact table for orders with business metrics
  tags:
  - marts
  - fct
  meta:
    model_type: fact
    source_models:
    - stg_orders
- name: dim_cart_items
  description: Dimension table for cart_items with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_cart_items
- name: dim_categories
  description: Dimension table for categories with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_categories
- name: dim_coupon_usage
  description: Dimension table for coupon_usage with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_coupon_usage
- name: dim_coupons
  description: Dimension table for coupons with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_coupons
- name: dim_product_images
  description: Dimension table for product_images with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_product_images
- name: dim_product_reviews
  description: Dimension table for product_reviews with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_product_reviews
- name: dim_product_variants
  description: Dimension table for product_variants with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_product_variants
- name: dim_products
  description: Dimension table for products with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_products
- name: dim_user_addresses
  description: Dimension table for user_addresses with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_user_addresses
- name: dim_users
  description: Dimension table for users with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_users
- name: dim_wishlist_items
  description: Dimension table for wishlist_items with descriptive attributes
  tags:
  - marts
  - dim
  meta:
    model_type: dimension
    source_models:
    - stg_wishlist_items
