version: 2
models:
- name: stg_cart_items
  description: Staging model for ecommerce.cart_items. Cleans and standardizes raw
    data.
  columns:
  - name: cart_item_id
    description: Cart Item Id
    data_type: uuid
  - name: user_id
    description: User Id
    data_type: uuid
  - name: product_id
    description: Product Id
    data_type: uuid
  - name: variant_id
    description: Variant Id
    data_type: uuid
  - name: quantity
    description: Quantity
    data_type: integer
  - name: added_at
    description: Added At
    data_type: timestamp
  - name: updated_at
    description: Updated At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.cart_items
- name: stg_categories
  description: Staging model for ecommerce.categories. Cleans and standardizes raw
    data.
  columns:
  - name: category_id
    description: Category Id
    data_type: uuid
  - name: name
    description: Name
    data_type: varchar
  - name: description
    description: Description
    data_type: text
  - name: parent_category_id
    description: Parent Category Id
    data_type: uuid
  - name: image_url
    description: Image Url
    data_type: varchar
  - name: is_active
    description: Is Active
    data_type: boolean
  - name: created_at
    description: Created At
    data_type: timestamp
  - name: updated_at
    description: Updated At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.categories
- name: stg_coupon_usage
  description: Staging model for ecommerce.coupon_usage. Cleans and standardizes raw
    data.
  columns:
  - name: usage_id
    description: Usage Id
    data_type: uuid
  - name: coupon_id
    description: Coupon Id
    data_type: uuid
  - name: user_id
    description: User Id
    data_type: uuid
  - name: order_id
    description: Order Id
    data_type: uuid
  - name: discount_amount
    description: Discount Amount
    data_type: numeric
  - name: used_at
    description: Used At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.coupon_usage
- name: stg_coupons
  description: Staging model for ecommerce.coupons. Cleans and standardizes raw data.
  columns:
  - name: coupon_id
    description: Coupon Id
    data_type: uuid
  - name: code
    description: Code
    data_type: varchar
  - name: description
    description: Description
    data_type: varchar
  - name: discount_type
    description: Discount Type
    data_type: varchar
  - name: discount_value
    description: Discount Value
    data_type: numeric
  - name: minimum_order_amount
    description: Minimum Order Amount
    data_type: numeric
  - name: maximum_discount_amount
    description: Maximum Discount Amount
    data_type: numeric
  - name: usage_limit
    description: Usage Limit
    data_type: integer
  - name: used_count
    description: Used Count
    data_type: integer
  - name: valid_from
    description: Valid From
    data_type: timestamp
  - name: valid_until
    description: Valid Until
    data_type: timestamp
  - name: is_active
    description: Is Active
    data_type: boolean
  - name: created_at
    description: Created At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  - not_null
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.coupons
- name: stg_order_items
  description: Staging model for ecommerce.order_items. Cleans and standardizes raw
    data.
  columns:
  - name: order_item_id
    description: Order Item Id
    data_type: uuid
  - name: order_id
    description: Order Id
    data_type: uuid
  - name: product_id
    description: Product Id
    data_type: uuid
  - name: variant_id
    description: Variant Id
    data_type: uuid
  - name: quantity
    description: Quantity
    data_type: integer
  - name: unit_price
    description: Unit Price
    data_type: numeric
  - name: total_price
    description: Total Price
    data_type: numeric
  - name: created_at
    description: Created At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  - not_null
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.order_items
- name: stg_orders
  description: Staging model for ecommerce.orders. Cleans and standardizes raw data.
  columns:
  - name: order_id
    description: Order Id
    data_type: uuid
  - name: user_id
    description: User Id
    data_type: uuid
  - name: order_number
    description: Order Number
    data_type: varchar
  - name: status
    description: Status
    data_type: varchar
  - name: total_amount
    description: Total Amount
    data_type: numeric
  - name: tax_amount
    description: Tax Amount
    data_type: numeric
  - name: shipping_amount
    description: Shipping Amount
    data_type: numeric
  - name: discount_amount
    description: Discount Amount
    data_type: numeric
  - name: shipping_address_id
    description: Shipping Address Id
    data_type: uuid
  - name: billing_address_id
    description: Billing Address Id
    data_type: uuid
  - name: payment_method
    description: Payment Method
    data_type: varchar
  - name: payment_status
    description: Payment Status
    data_type: varchar
  - name: notes
    description: Notes
    data_type: text
  - name: created_at
    description: Created At
    data_type: timestamp
  - name: updated_at
    description: Updated At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.orders
- name: stg_product_images
  description: Staging model for ecommerce.product_images. Cleans and standardizes
    raw data.
  columns:
  - name: image_id
    description: Image Id
    data_type: uuid
  - name: product_id
    description: Product Id
    data_type: uuid
  - name: image_url
    description: Image Url
    data_type: varchar
  - name: alt_text
    description: Alt Text
    data_type: varchar
  - name: is_primary
    description: Is Primary
    data_type: boolean
  - name: sort_order
    description: Sort Order
    data_type: integer
  - name: created_at
    description: Created At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.product_images
- name: stg_product_reviews
  description: Staging model for ecommerce.product_reviews. Cleans and standardizes
    raw data.
  columns:
  - name: review_id
    description: Review Id
    data_type: uuid
  - name: product_id
    description: Product Id
    data_type: uuid
  - name: user_id
    description: User Id
    data_type: uuid
  - name: rating
    description: Rating
    data_type: integer
  - name: title
    description: Title
    data_type: varchar
  - name: review_text
    description: Review Text
    data_type: text
  - name: is_verified_purchase
    description: Is Verified Purchase
    data_type: boolean
  - name: is_approved
    description: Is Approved
    data_type: boolean
  - name: created_at
    description: Created At
    data_type: timestamp
  - name: updated_at
    description: Updated At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.product_reviews
- name: stg_product_variants
  description: Staging model for ecommerce.product_variants. Cleans and standardizes
    raw data.
  columns:
  - name: variant_id
    description: Variant Id
    data_type: uuid
  - name: product_id
    description: Product Id
    data_type: uuid
  - name: variant_name
    description: Variant Name
    data_type: varchar
  - name: variant_type
    description: Variant Type
    data_type: varchar
  - name: price_adjustment
    description: Price Adjustment
    data_type: numeric
  - name: stock_quantity
    description: Stock Quantity
    data_type: integer
  - name: sku
    description: Sku
    data_type: varchar
  - name: is_active
    description: Is Active
    data_type: boolean
  - name: created_at
    description: Created At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.product_variants
- name: stg_products
  description: Staging model for ecommerce.products. Cleans and standardizes raw data.
  columns:
  - name: product_id
    description: Product Id
    data_type: uuid
  - name: name
    description: Name
    data_type: varchar
  - name: description
    description: Description
    data_type: text
  - name: sku
    description: Sku
    data_type: varchar
  - name: category_id
    description: Category Id
    data_type: uuid
  - name: price
    description: Price
    data_type: numeric
  - name: sale_price
    description: Sale Price
    data_type: numeric
  - name: cost_price
    description: Cost Price
    data_type: numeric
  - name: weight
    description: Weight
    data_type: numeric
  - name: dimensions
    description: Dimensions
    data_type: varchar
  - name: stock_quantity
    description: Stock Quantity
    data_type: integer
  - name: min_stock_level
    description: Min Stock Level
    data_type: integer
  - name: is_active
    description: Is Active
    data_type: boolean
  - name: is_featured
    description: Is Featured
    data_type: boolean
  - name: created_at
    description: Created At
    data_type: timestamp
  - name: updated_at
    description: Updated At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  - not_null
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.products
- name: stg_user_addresses
  description: Staging model for ecommerce.user_addresses. Cleans and standardizes
    raw data.
  columns:
  - name: address_id
    description: Address Id
    data_type: uuid
  - name: user_id
    description: User Id
    data_type: uuid
  - name: address_type
    description: Address Type
    data_type: varchar
  - name: street_address
    description: Street Address
    data_type: varchar
  - name: city
    description: City
    data_type: varchar
  - name: state
    description: State
    data_type: varchar
  - name: postal_code
    description: Postal Code
    data_type: varchar
  - name: country
    description: Country
    data_type: varchar
  - name: is_default
    description: Is Default
    data_type: boolean
  - name: created_at
    description: Created At
    data_type: timestamp
  tests:
  - not_null
  - unique
  - not_null
  - not_null
  - not_null
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.user_addresses
- name: stg_users
  description: Staging model for ecommerce.users. Cleans and standardizes raw data.
  columns:
  - name: user_id
    description: User Id
    data_type: uuid
  - name: email
    description: Email
    data_type: varchar
  - name: password_hash
    description: Password Hash
    data_type: varchar
  - name: first_name
    description: First Name
    data_type: varchar
  - name: last_name
    description: Last Name
    data_type: varchar
  - name: phone
    description: Phone
    data_type: varchar
  - name: date_of_birth
    description: Date Of Birth
    data_type: date
  - name: created_at
    description: Created At
    data_type: timestamp
  - name: updated_at
    description: Updated At
    data_type: timestamp
  - name: is_active
    description: Is Active
    data_type: boolean
  - name: email_verified
    description: Email Verified
    data_type: boolean
  tests:
  - not_null
  - unique
  - not_null
  - not_null
  - not_null
  - not_null
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.users
- name: stg_wishlist_items
  description: Staging model for ecommerce.wishlist_items. Cleans and standardizes
    raw data.
  columns:
  - name: wishlist_item_id
    description: Wishlist Item Id
    data_type: uuid
  - name: user_id
    description: User Id
    data_type: uuid
  - name: product_id
    description: Product Id
    data_type: uuid
  - name: added_at
    description: Added At
    data_type: timestamp
  tests:
  - not_null
  - unique
  tags:
  - staging
  - ecommerce
  meta:
    source_table: ecommerce.wishlist_items
