version: 2
sources:
- name: ecommerce
  description: Raw data from ecommerce schema
  tables:
  - name: cart_items
    description: Raw cart_items data
  - name: categories
    description: Raw categories data
  - name: coupon_usage
    description: Raw coupon_usage data
  - name: coupons
    description: Raw coupons data
  - name: order_items
    description: Raw order_items data
  - name: orders
    description: Raw orders data
  - name: product_images
    description: Raw product_images data
  - name: product_reviews
    description: Raw product_reviews data
  - name: product_variants
    description: Raw product_variants data
  - name: products
    description: Raw products data
  - name: user_addresses
    description: Raw user_addresses data
  - name: users
    description: Raw users data
  - name: wishlist_items
    description: Raw wishlist_items data
