name: generated_dbt_project
version: 1.0.0
config-version: 2
profile: generated_dbt_project
model-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- seeds
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
clean-targets:
- target
- dbt_packages
- logs
models:
  generated_dbt_project:
    staging:
      +materialized: view
      +tags:
      - staging
    intermediate:
      +materialized: view
      +tags:
      - intermediate
    marts:
      +materialized: table
      +tags:
      - marts
      core:
        +tags:
        - marts
        - core
tests:
  +store_failures: true
vars:
  start_date: '2020-01-01'
  timezone: UTC
